# **IMPORT LIBRARIES**

In [2]:

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [3]:
pip install seaborn

Requirement already satisfied: seaborn in c:\users\asus\documents\mds\ey intership\eta-delay-prediction-logistics\.venv1\lib\site-packages (0.13.2)
Requirement already satisfied: pandas>=1.2 in c:\users\asus\documents\mds\ey intership\eta-delay-prediction-logistics\.venv1\lib\site-packages (from seaborn) (2.3.3)
Requirement already satisfied: numpy!=1.24.0,>=1.20 in c:\users\asus\documents\mds\ey intership\eta-delay-prediction-logistics\.venv1\lib\site-packages (from seaborn) (2.2.6)
Requirement already satisfied: matplotlib!=3.6.1,>=3.4 in c:\users\asus\documents\mds\ey intership\eta-delay-prediction-logistics\.venv1\lib\site-packages (from seaborn) (3.10.8)
Requirement already satisfied: contourpy>=1.0.1 in c:\users\asus\documents\mds\ey intership\eta-delay-prediction-logistics\.venv1\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (1.3.2)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\asus\documents\mds\ey intership\eta-delay-prediction-logistics\.venv1\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (4.62.0)
Requirement already satisfied: python-dateutil>=2.7 in c:\users\asus\documents\mds\ey intership\eta-delay-prediction-logistics\.venv1\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (2.9.0.post0)
Requirement already satisfied: cycler>=0.10 in c:\users\asus\documents\mds\ey intership\eta-delay-prediction-logistics\.venv1\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (0.12.1)
Requirement already satisfied: pyparsing>=3 in c:\users\asus\documents\mds\ey intership\eta-delay-prediction-logistics\.venv1\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (3.3.2)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\users\asus\documents\mds\ey intership\eta-delay-prediction-logistics\.venv1\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (1.5.0)
Requirement already satisfied: packaging>=20.0 in c:\users\asus\documents\mds\ey intership\eta-delay-prediction-logistics\.venv1\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (26.0)
Requirement already satisfied: pillow>=8 in c:\users\asus\documents\mds\ey intership\eta-delay-prediction-logistics\.venv1\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (12.1.1)
Requirement already satisfied: tzdata>=2022.7 in c:\users\asus\documents\mds\ey intership\eta-delay-prediction-logistics\.venv1\lib\site-packages (from pandas>=1.2->seaborn) (2025.3)
Requirement already satisfied: pytz>=2020.1 in c:\users\asus\documents\mds\ey intership\eta-delay-prediction-logistics\.venv1\lib\site-packages (from pandas>=1.2->seaborn) (2026.1.post1)
Requirement already satisfied: six>=1.5 in c:\users\asus\documents\mds\ey intership\eta-delay-prediction-logistics\.venv1\lib\site-packages (from python-dateutil>=2.7->matplotlib!=3.6.1,>=3.4->seaborn) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip available: 22.3.1 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [4]:

import seaborn as sns

In [5]:
pd.set_option('display.max_columns', None)
pd.set_option('display.width', 120)

## **Holiday API**

**Holiday API**

In [7]:
import pandas as pd

df = pd.read_csv("../Data/Added_Holiday_Features_dataset.csv")

[col for col in df.columns if "holiday" in col.lower()]

['transit_holidays',
 'holiday_count_transit',
 'holiday_names_transit',
 'holiday_or_weekend_transit_flag',
 'holiday_proximity_feature']

In [8]:
print("Column Names:\n")

for col in df.columns:
    print(col)

Column Names:

delivery_id
delivery_partner
package_type
vehicle_type
delivery_mode
region
weather_condition
distance_km
package_weight_kg
delayed
delivery_status
delivery_rating
delivery_cost
expected_time_hours_recon
speed_kmph_recon
weather_mult_recon
delivery_time_hours_recon
partner_mult_recon
delay_hours_recon
delayed_flag_recon
order_date_recon
order_ts_recon
delivery_ts_recon
expected_ts_recon
hour
order_date
expected_date
transit_holidays
holiday_count_transit
holiday_names_transit
weekend_count_transit
holiday_or_weekend_transit_flag
holiday_proximity_feature

In [9]:
df.head()

,delivery_id,delivery_partner,package_type,vehicle_type,delivery_mode,region,weather_condition,distance_km,package_weight_kg,delayed,delivery_status,delivery_rating,delivery_cost,expected_time_hours_recon,speed_kmph_recon,weather_mult_recon,delivery_time_hours_recon,partner_mult_recon,delay_hours_recon,delayed_flag_recon,order_date_recon,order_ts_recon,delivery_ts_recon,expected_ts_recon,hour,order_date,expected_date,transit_holidays,holiday_count_transit,holiday_names_transit,weekend_count_transit,holiday_or_weekend_transit_flag,holiday_proximity_feature
0,250.99,amazon logistics,automobile parts,ev bike,standard,west,clear,235.6,48.07,no,delivered,5,1322.21,52.8,30,1.0,9.332489,1.001906,-43.467511,0,21-10-2024,2024-10-21 13:00:00,2024-10-21 22:19:56.959673890,2024-10-23 17:48:00,13,2024-10-21,2024-10-23,[],0,NaN,0,0,1
1,250.99,amazon logistics,clothing,bike,express,central,stormy,81.8,45.51,yes,delayed,2,595.53,8.0,35,1.1,4.129935,1.001906,-3.870065,0,02-01-2024,2024-01-02 12:00:00,2024-01-02 16:07:47.764281093,2024-01-02 20:00:00,12,2024-01-02,2024-01-02,[],0,NaN,0,0,1
2,250.99,amazon logistics,clothing,van,same day,north,clear,282.9,31.33,yes,delayed,2,1608.49,26.4,45,1.0,7.427398,1.001906,-18.972602,0,31-05-2024,2024-05-31 11:00:00,2024-05-31 18:25:38.631406710,2024-06-01 13:24:00,11,2024-05-31,2024-06-01,[],0,NaN,1,1,8
3,250.99,amazon logistics,cosmetics,ev bike,two day,central,hot,88.6,8.67,no,delivered,3,469.01,48.0,30,1.1,3.997011,1.001906,-44.002989,0,03-01-2024,2024-01-03 17:00:00,2024-01-03 20:59:49.240153885,2024-01-05 17:00:00,17,2024-01-03,2024-01-05,[],0,NaN,0,0,2
4,250.99,amazon logistics,cosmetics,ev van,two day,east,rainy,204.2,8.09,no,delivered,4,1045.27,52.8,40,1.2,6.933351,1.001906,-45.866649,0,19-03-2024,2024-03-19 13:00:00,2024-03-19 19:56:00.063604276,2024-03-21 17:48:00,13,2024-03-19,2024-03-21,['March Equinox'],1,March Equinox,0,1,1

- Integrated **Calendarific Holiday API** to dynamically fetch Indian national holidays.

- Extracted the **years present in the dataset** and requested holiday data for those years.

- Cleaned and converted **order and expected delivery timestamps** to proper datetime format.

- Cached the API results locally as **`india_holidays_cached.csv`** to avoid repeated API calls and improve pipeline efficiency.

- Engineered **transit-based holiday features** between order date and expected delivery date.

- Created new features:
  - `holiday_count_transit`
  - `holiday_names_transit`
  - `weekend_count_transit`
  - `holiday_or_weekend_transit_flag`
  - `holiday_proximity_feature`

- Saved the enriched dataset as **`Added_Holiday_Features_dataset.csv`** for further modeling and analysis.

Weather API

In [11]:
import pandas as pd

df = pd.read_csv("../Data/dataset_with_weather_features.csv")

[col for col in df.columns if "weather" in col.lower()]

['weather_condition', 'weather_mult_recon', 'bad_weather_flag_api']

In [12]:
print("Column Names:\n")

for col in df.columns:
    print(col)

Column Names:

delivery_id
delivery_partner
package_type
vehicle_type
delivery_mode
region
weather_condition
distance_km
package_weight_kg
delayed
delivery_status
delivery_rating
delivery_cost
expected_time_hours_recon
speed_kmph_recon
weather_mult_recon
delivery_time_hours_recon
partner_mult_recon
delay_hours_recon
delayed_flag_recon
order_date_recon
order_ts_recon
delivery_ts_recon
expected_ts_recon
hour
order_date
expected_date
transit_holidays
holiday_count_transit
holiday_names_transit
weekend_count_transit
holiday_or_weekend_transit_flag
holiday_proximity_feature
api_temperature
api_humidity
api_wind_speed
bad_weather_flag_api

In [13]:
df.head()

,delivery_id,delivery_partner,package_type,vehicle_type,delivery_mode,region,weather_condition,distance_km,package_weight_kg,delayed,delivery_status,delivery_rating,delivery_cost,expected_time_hours_recon,speed_kmph_recon,weather_mult_recon,delivery_time_hours_recon,partner_mult_recon,delay_hours_recon,delayed_flag_recon,order_date_recon,order_ts_recon,delivery_ts_recon,expected_ts_recon,hour,order_date,expected_date,transit_holidays,holiday_count_transit,holiday_names_transit,weekend_count_transit,holiday_or_weekend_transit_flag,holiday_proximity_feature,api_temperature,api_humidity,api_wind_speed,bad_weather_flag_api
0,250.99,amazon logistics,automobile parts,ev bike,standard,west,clear,235.6,48.07,no,delivered,5,1322.21,52.8,30,1.0,9.332489,1.001906,-43.467511,0,21-10-2024,2024-10-21 13:00:00,2024-10-21 22:19:56.959673890,2024-10-23 17:48:00,13,2024-10-21,2024-10-23,[],0,NaN,0,0,1,32.907296,13.868897,5.097329,0
1,250.99,amazon logistics,clothing,bike,express,central,stormy,81.8,45.51,yes,delayed,2,595.53,8.0,35,1.1,4.129935,1.001906,-3.870065,0,02-01-2024,2024-01-02 12:00:00,2024-01-02 16:07:47.764281093,2024-01-02 20:00:00,12,2024-01-02,2024-01-02,[],0,NaN,0,0,1,34.858216,8.535792,5.187116,1
2,250.99,amazon logistics,clothing,van,same day,north,clear,282.9,31.33,yes,delayed,2,1608.49,26.4,45,1.0,7.427398,1.001906,-18.972602,0,31-05-2024,2024-05-31 11:00:00,2024-05-31 18:25:38.631406710,2024-06-01 13:24:00,11,2024-05-31,2024-06-01,[],0,NaN,1,1,8,34.384286,13.161405,4.840818,0
3,250.99,amazon logistics,cosmetics,ev bike,two day,central,hot,88.6,8.67,no,delivered,3,469.01,48.0,30,1.1,3.997011,1.001906,-44.002989,0,03-01-2024,2024-01-03 17:00:00,2024-01-03 20:59:49.240153885,2024-01-05 17:00:00,17,2024-01-03,2024-01-05,[],0,NaN,0,0,2,31.945980,9.940262,4.831139,0
4,250.99,amazon logistics,cosmetics,ev van,two day,east,rainy,204.2,8.09,no,delivered,4,1045.27,52.8,40,1.2,6.933351,1.001906,-45.866649,0,19-03-2024,2024-03-19 13:00:00,2024-03-19 19:56:00.063604276,2024-03-21 17:48:00,13,2024-03-19,2024-03-21,['March Equinox'],1,March Equinox,0,1,1,34.351108,10.819839,5.223025,1

- Integrated **OpenWeatherMap API** to obtain weather information for logistics deliveries.

- Extracted **all unique transit dates** between `order_date` and `expected_date` from the dataset.

- Fetched weather data using the API based on **latitude and longitude coordinates** of the logistics region.

- Since the free API does not support historical weather data, **current weather values were used as a baseline**.

- Introduced **small stochastic variations (random noise)** to simulate realistic day-to-day weather changes for past dates.

- Cached the retrieved weather information locally as **`weather_cached.csv`** to avoid repeated API calls.

- Mapped weather data to each delivery by calculating the **average weather conditions during the transit period**.

- The bad_weather_flag_api is set to 1 if the weather condition indicates rain, storm, fog, or snow, or if API wind speed > 10 m/s or API humidity > 85%; otherwise it is 0.

- Created new weather-related features:
  - `api_temperature`
  - `api_humidity`
  - `api_wind_speed`
  - `bad_weather_flag_api`

- The final enriched dataset was saved as **`dataset_with_weather_features.csv`** for further machine learning modeling.

In [15]:
import pandas as pd #Final List of features added to the dataset 

df = pd.read_csv("../Data/dataset_with_weather_features.csv")

[col for col in df.columns if ("holiday" in col.lower()) or ("weather" in col.lower())]

['weather_condition',
 'weather_mult_recon',
 'transit_holidays',
 'holiday_count_transit',
 'holiday_names_transit',
 'holiday_or_weekend_transit_flag',
 'holiday_proximity_feature',
 'bad_weather_flag_api']